/**
 * Service Order Factory Function
 * @param {number} id - Unique identifier generated by the system
 * @param {string} customer - Name of the person requesting the service
 * @param {string} description - Details of the service order
 */

const createOrder = (id, custumer, description) => {
    return {
        id: id,
        custumerName: custumer,
        description: description,
        status: "OPEN",
        createdAt: new Date()
    };
};

module.exports = {createOrder};